name: json_to_dart
version: 0.0.1
author: liu<228669797@qq.com>
description: Read the JSON file and generate dart class to the specified directory.
homepage: https://github.com/fromgz/json_to_dart

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  json_ast: "^1.0.5"
  convert: "^2.0.1"
  dart_style: "^1.0.10"

dev_dependencies:
  test: "^1.9.4"
  path: "^1.6.4"
